### ISSUE TITLE
Tests run twice on windows

### ISSUE THREAD

**Issue by cschneid** [urbint/cortex#9] opened 2017-07-13 02:55 UTC
I'm new to developing on windows, so I'm unsure if this is particularly windows related, or what, but I am seeing tests run twice on every save of a test file.

Windows 10, ConEmu + cmd.exe, Atom, Elixir 1.4.4, Phoenix 1.3.0pre2 (brand new app).

```
set MIX_ENV=test

> iex -S mix
Eshell V8.3  (abort with ^G)
Interactive Elixir (1.4.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> .iex(1)>

### A SINGLE SAVE of test/myapp/web/controllers/page_controller_test.exs

iex(1)> Finished in 0.06 seconds
iex(1)> 1 test, 0 failures
iex(1)>
Randomized with seed 278000
iex(1)> .iex(1)>

iex(1)> Finished in 0.00 seconds
iex(1)> 1 test, 0 failures
iex(1)>
Randomized with seed 396000
```

**Comment by OvermindDL1** [comment] 2017-07-20 20:22
Confirmed here on Windows 10 as well, 2 tests are being run.  It looks like a debounce should probably be done on some file listener I'd guess.

**Comment by rschmukler** [comment] 2017-07-20 22:05
Thanks for the confirmation.

This is likely a bug with [exfswatch](https://github.com/falood/exfswatch) which is what Cortex uses for file watching. I'd suggest an issue be opened there / perhaps a PR submitted for the debouncing mentioned.

**Comment by OvermindDL1** [comment] 2017-07-21 14:47
> I'd suggest an issue be opened there / perhaps a PR submitted for the debouncing mentioned.

I'm not sure the debouncing should exist in it, it should just report the events.  Windows submits more events due to the way that NTFS works and sometimes each is useful in its own way.

**Comment by jeffdeville** [comment] 2017-07-24 13:49
I'm getting the same issue for an umbrella project on osx.  I put a log statement in FileWatcher though, and there was only 1 file change event.

**Comment by rschmukler** [comment] 2017-07-26 01:32
@jeffdeville that's quite peculiar. Our primary env for Cortex is an umbrella project on OSX machines. Did you debug any further? Any insights you could share?

**Comment by jeffdeville** [comment] 2017-07-26 09:41
Yeah, it's only on 1 of my projects that this has been happening.  I'll keep an eye on it and try and get more info for you.

**Comment by jeffdeville** [comment] 2017-07-26 14:10
@rschmukler Ok, working on the affected project.  When cortex triggers the run of a test, it runs all of the test twice, but it does so in an unexpected manner:

If I run a test with just mix test PATH, it'll execute 10 tests.  But when cortex runs the same file, exunit tells me it has executed 20 tests.

I dropped some logging in the test_runner.ex just to see what files are being loaded, and it all looks normal.

:run_tests_for_file - /PATH/apps/search/test/lib/repo_test.exs
Files Loaded: ["test/test_helper.exs", "/PATH/apps/search/test/lib/repo_test.exs"]

So in my case, I *think* the problem is somewhere in here:

```elixir
task = Task.async(ExUnit, :run, [])
ExUnit.Server.cases_loaded()
```

Does that help?

**Comment by rschmukler** [comment] 2017-10-09 15:44
@jeffdeville I suspect that this will be fixed by #21. Can you let us know (once it lands) if it is resolved?

**Comment by mmport80** [comment] 2017-12-07 17:12
On Win10 with

{:cortex, "~> 0.4.2", only: [:dev, :test]}

my tests run x4.

Any thoughts? Anything I can help with?

**Comment by OvermindDL1** [comment] 2017-12-08 15:31
> my tests run x4.

I even get this on linux now that I'm deving exclusively there now too...  >.>

**Comment by glittershark** [comment] 2017-12-08 16:51
@OvermindDL1 I'm on Linux too, so I feel the pain. I haven't had the proper time in the last couple of months to finish up #21, but am hoping to get around to it over the holidays

**Closed as completed** 2020-01-27 15:48 UTC
